language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn test -DskipDataPackaging=true -B

deploy:
  provider: script
  script: ./deployment/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - # After lots of trial and error, I discovered that the encryption ought to be performed as -> travis encrypt "OSSRH_JIRA_USERNAME='username with spaces and @ symbols'"
    - secure: "ahWsLz3H+YAxadhdhJ8G0Vw7PZIIuPCxoQkF+SrxG08KXNIoRJrXBh+ALuhRImYAU+HP/qRZLbrAXOEnQPt+1B5ehtLLCce+Ea3kGbNF2h9pIbT6CWB/Eh/zJwOXL156ylBzmlIrzmSe6oRiXGeuHeD3OTuoFlG69nfu0+MTjUjVgyo500XdCAa8JdouR5sUpKJJMg/COcGfSzfLi6Ot+VMgjVNRdx1jJCF0SmgBXY0ckfROV2yMHrGS7zBFUdaln75/egmaX31p4ksDFLIkIHyh74xk2hYInAZ3FichPqD+r++ghrC/5Xsf+VaA3Jvsso/CKpXn1qTqwVdqC7tLyxJzE26DxkAQlyFx5uYb2jA+xO5wO353Oh7hIgxFcAqlpGcOl68hA3GY1STHTHaY1J2ZBDpnXvgQHydbgJh7x6Uyl0gBaiGaD7RdgoxqXUhog+L/ZR7k/i66o3swBMjZVUFMEILUaVMMlVjTPtlUryjXovo370Ocs/yDTaFpokCyI0IHZC8aeu3DNWwX3dMH2Ll3I6DmD220novMIDFhkS+KYXBFQY16qJQziYGG3odufOsbaYErKizMOLoc9rx0OXFACS8XVXSTy0PUVlIpv10hGZC6hXOYKn2xHuAEao5HmDbH0TS6kXQ5yj4C3EGjzG6RDSFhkrx5GsREtaOB2bA="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "babZA3Efcp5iZ2a6zkUfze45RRwUnGTQLanBXbgTwzg+MKAWy/9GEf7XV4hgsiiVDsgn7nxWd4B04AHE5MibHBO2fvF1Kc0gp0gj98GlKw+BoVyMmvDTCi+LawAOVA+W8C0loDRT/6x/hUoS/bVihdmmqU6jk9RlY1vTw0k7I+4IXCX4RCaVd/fR+hsSjXAgqJTGvgj90KkomY167i/nimCMLc2CiiRRzYAmdjPqDDC202ZKOLLCooA9Fu0x98uj2HDlG3b6t3M31ZCxMNNbFSb0KPFAZiF3TZGtnJSNW0Cd1LeXVRDv78a/fVjo8dOhvZJvIjv/RqNN8TdGenYllPiD1bUZ5mFOS+f3MnfJXPpm2M6fVJKENTrWJVvBB1lI/KTWxk3BqEb7b9V505v0K5rblJQG4dRRoJZ56c/0DKJBesn2RVEPpqTC9VXtAMf35JLDjom+m21evBGrTBUc5KO4Sope3ZK4Bke3MFOVIKZX/UjELgAVW7xd/97QKUDSmqJP0DUsxesN0HCCQk8+YzOWsswLI5Qj8LD/gsASWc0K1azm/sJs3GrRNhH0wkh9KfcEkhCi45OZyThjDKyW7k3mlXqhejKu9DOE23zML3Foqv9ZL5QG++cLqxTBCw+DVKI1AMx0/ynTwPOHDidUgj7M03fPL/RFFPjT2RFj0/4="
    - # ^^ GPG_KEY_NAME
    - secure: "h+z9MFUXZSuM1j96fqr1m/mSxKE0WnzNpbZXcOG70EQQX3DcDsZ8G/7baVwb4Zy7AtPHVmGoUt5ms7iw1qWC/F4eL/qs1V6vEWlrRxMUgK/LOzCE5wlthYtTxeyObD5+MDBA6acj0ey/RcdNpAT1VcIX60ivQu1K6WMYYyUdIyh0IJ8m0eGPDp9tMYOaFxBBSnDMh7Tq0qMpsulvUEvbLOvQr4v4+qturO9Sc+ytiLZXYWuarJB/ou7hK/ex8ZuwrVNHFd2m6DLQhrGXN0LM+hZVKgHsHr+bHmw6a/U7PgQk2ZPd+HC6tAakdBxOT6ZzM1dm6Rght+XZIkezXJTLR7QNHvYoOtoMByFgd0x7NRAk5OXLngggaOAc45Tz5iUnpxPOHoxHTLwI2mcDUa2yBk6xZDEqqTQfaIIKJES6dy1NTJfO+15p4rgqFkLZD0AK9AWwDTBu6YiWOb5vqlVfsG6fSna6y/AGZ+VdqohstfcfV10Evo+9BQH1vtfzXRdeiZqK6aSYersZFW+8zsvII0KPsLEYRXEE8xxQg1zPcyD2k2TP24zkuPphVFSiNt8qMat+C2tXykPuaUhr0Pct9lW1OiTrXnNTFMjygvJER9v85UIJYlRkVfxrLqTKk5xDGpBPcOXnVX6CUGdrk7HG6bxjALeRHLnytatKA7/+zAQ="
    - # ^^ GPG_PASSPHRASE
